overrides:
  jackspeak: 2.1.1
  axios@>=1.3.2 <=1.7.3: '>=1.7.4'
  micromatch@<4.0.8: '>=4.0.8'
  webpack@>=5.0.0-alpha.0 <5.94.0: '>=5.94.0'
  nanoid@<3.3.8: '>=3.3.8'
  axios@>=1.0.0 <1.8.2: '>=1.8.2'
  '@babel/runtime@<7.26.10': '>=7.26.10'
  cross-spawn@>=7.0.0 <7.0.5: '>=7.0.5'
  brace-expansion@>=1.0.0 <=1.1.11: '>=1.1.12'
  brace-expansion@>=2.0.0 <=2.0.1: '>=2.0.2'
