import './globals.css'
import type { Metadata } from 'next'
import { outfit, patrick_hand } from './fonts'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${outfit.className} ${outfit.variable} ${patrick_hand.variable}`}>{children}</body>
    </html>
  )
}
